services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: always
    volumes:
      - /home/docker_service/docker_app/neo4j/logs:/var/lib/neo4j/logs
      - /home/docker_service/docker_app/neo4j/config:/var/lib/neo4j/conf
      - /home/docker_service/docker_app/neo4j/data:/var/lib/neo4j/data
      - /home/docker_service/docker_app/neo4j/plugins:/var/lib/neo4j/plugins
    environment:
      - NEO4J_AUTH=neo4j/123456
    ports:
      - "9012:7474"
      - "9013:7687"
